import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Todo List</h1>

        <div className={styles.grid}>
          <Link href="/todo">
            <a className={styles.card}>
              <h2>Create a new Todo&rarr;</h2>
              <p>Create your daily todos and add them to your list.</p>
            </a>
          </Link>
          <Link href="/deleted-tods">
            <a className={styles.card}>
              <h2>Deleted todos &rarr;</h2>
              <p>Deleted todos that you can Recycle again.</p>
            </a>
          </Link>
          <Link href="/completed-todos">
            <a className={styles.card}>
              <h2>Completed todos&rarr;</h2>
              <p>You can see your completed todos</p>
            </a>
          </Link>
          <Link href="/pending-todos">
            <a className={styles.card}>
              <h2>Pending todos&rarr;</h2>
              <p>You can see your non completed todos</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
